import type { PriorityInput } from '@/lib/roi-calculator/types/confidence';
import type { EnabledModules } from '@/lib/roi-calculator/types/calculator';

// ── The Minimum Viable Inputs for a Credible ROI ─────────────────────
// These are the ~12 fields that drive 80%+ of the ROI calculation.
// Everything else can safely stay at benchmark defaults.
//
// Design principles:
// - Only ask what the prospect is likely to know off the top of their head
// - Group by conversational topic, not by technical module
// - Critical inputs = change the ROI by 20%+; High = 10-20%; Medium = 5-10%

export function getPriorityInputs(
  currencySymbol: string,
  country: string,
  hotelType: string,
  enabledModules?: EnabledModules,
): PriorityInput[] {
  const inputs: PriorityInput[] = [
    // ── Group 1: Property Basics (everyone knows these) ──────────────
    {
      key: 'sharedVariables.numberOfRooms',
      slice: 'sharedVariables',
      field: 'numberOfRooms',
      label: 'Number of Rooms',
      question: 'How many rooms does your property have?',
      benchmarkLabel: `Typical ${hotelType} size`,
      unit: 'rooms',
      min: 1,
      max: 1000,
      step: 1,
      group: 'property',
      importance: 'critical',
      benchmarkSourceInfo: `Based on average room counts for ${hotelType} properties from STR/CoStar industry reports and Mews research across similar properties.`,
    },
    {
      key: 'sharedVariables.averageDailyRate',
      slice: 'sharedVariables',
      field: 'averageDailyRate',
      label: 'Average Daily Rate (ADR)',
      question: `What's your average room rate?`,
      benchmarkLabel: `${hotelType}s in ${country} average`,
      unit: currencySymbol,
      min: 1,
      max: 1000,
      step: 5,
      group: 'property',
      importance: 'critical',
      benchmarkSourceInfo: `Average daily rate for ${hotelType}s in ${country}, sourced from STR/CoStar benchmarking data and CBRE Hotels Trends report.`,
    },
    {
      key: 'sharedVariables.occupancyRate',
      slice: 'sharedVariables',
      field: 'occupancyRate',
      label: 'Occupancy Rate',
      question: `What's your average annual occupancy?`,
      benchmarkLabel: `${hotelType}s in ${country} average`,
      unit: '%',
      min: 10,
      max: 100,
      step: 1,
      group: 'property',
      importance: 'critical',
      benchmarkSourceInfo: `Occupancy rate for ${hotelType}s in ${country}, sourced from STR/CoStar Global benchmarking data and HotStats performance reports.`,
    },
    {
      key: 'sharedVariables.avgLengthOfStay',
      slice: 'sharedVariables',
      field: 'avgLengthOfStay',
      label: 'Average Length of Stay',
      question: 'What is your average length of stay in nights?',
      benchmarkLabel: `${
        hotelType === 'Serviced Apartment' ? '4.5'
        : hotelType === 'Short-Term Rental' ? '3.5'
        : hotelType === 'Conference Hotel' ? '2.2'
        : hotelType === 'Boutique Hotel' ? '1.8'
        : '1.7'
      } nights typical for ${hotelType}s`,
      unit: 'nights',
      min: 1,
      max: 30,
      step: 0.1,
      group: 'property',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Average length of stay for ${hotelType} properties based on STR/CoStar data and Mews research.`,
    },
    {
      key: 'sharedVariables.reservationsPerMonth',
      slice: 'sharedVariables',
      field: 'reservationsPerMonth',
      label: 'Reservations per Month',
      question: '',
      benchmarkLabel: 'Rooms x 30 x Occupancy / Avg Stay (auto-calculated)',
      unit: 'reservations',
      min: 1,
      max: 50000,
      step: 1,
      group: 'property',
      importance: 'high',
      readOnly: true,
      validationOnly: true,
      benchmarkSourceInfo: 'Derived from number of rooms, occupancy rate, and average length of stay.',
    },
    {
      key: 'sharedVariables.staffHourlyWage',
      slice: 'sharedVariables',
      field: 'staffHourlyWage',
      label: 'Staff Hourly Wage',
      question: `What does your front desk staff earn per hour, roughly?`,
      benchmarkLabel: `Hospitality average in ${country}`,
      unit: currencySymbol,
      min: 1,
      max: 100,
      step: 0.5,
      group: 'property',
      importance: 'high',
      skipLabel: 'Use national average',
      benchmarkSourceInfo: `Average hospitality staff wage in ${country}, sourced from national labor statistics and CBRE Hotels research.`,
    },

    // ── Group 2: Operations (reps usually know these) ────────────────
    {
      key: 'guestExperience.checkInTime',
      slice: 'guestExperience',
      field: 'checkInTime',
      label: 'Check-in Time',
      question: 'How many minutes does a typical guest check-in take today?',
      benchmarkLabel: `${hotelType} industry average`,
      unit: 'min',
      min: 1,
      max: 20,
      step: 0.5,
      group: 'operations',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Average check-in time for ${hotelType} properties based on Mews research and industry operator interviews measuring traditional front-desk processes.`,
      mewsMapping: {
        slice: 'guestExperience',
        field: 'mewsCheckInTime',
        label: 'With Mews',
        unit: 'min',
        min: 0.5,
        max: 10,
        step: 0.5,
        displayMode: 'target',
      },
    },
    {
      key: 'guestExperience.checkOutTime',
      slice: 'guestExperience',
      field: 'checkOutTime',
      label: 'Check-out Time',
      question: 'How many minutes does a typical guest check-out take?',
      benchmarkLabel: `${hotelType} industry average`,
      unit: 'min',
      min: 0.5,
      max: 10,
      step: 0.5,
      group: 'operations',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Average check-out time for ${hotelType} properties based on Mews research and industry operator interviews.`,
      mewsMapping: {
        slice: 'guestExperience',
        field: 'mewsCheckOutTime',
        label: 'With Mews',
        unit: 'min',
        min: 0,
        max: 5,
        step: 0.5,
        displayMode: 'target',
      },
    },
    {
      key: 'guestExperience.roomAssignmentTime',
      slice: 'guestExperience',
      field: 'roomAssignmentTime',
      label: 'Room Assignment Time',
      question: 'How many minutes does it take to manually assign a room to a reservation?',
      benchmarkLabel: `${hotelType === 'Conference Hotel' ? '3.0' : '2.5'} min industry average`,
      unit: 'min',
      min: 0,
      max: 10,
      step: 0.5,
      group: 'operations',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Average room assignment time for ${hotelType} properties based on Mews research and industry operator interviews.`,
      mewsLabel: 'Automated',
    },
    {
      key: 'payment.chargebackRate',
      slice: 'payment',
      field: 'chargebackRate',
      label: 'Chargeback Rate',
      question: 'What percentage of transactions result in chargebacks?',
      benchmarkLabel: 'Hospitality industry average 0.5-1%',
      unit: '%',
      min: 0,
      max: 5,
      step: 0.05,
      group: 'payments',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: 'Hospitality chargeback rates sourced from HFTP (Hospitality Financial and Technology Professionals) research and payment processor industry data.',
      mewsMapping: {
        slice: 'payment',
        field: 'mewsChargebackRate',
        label: 'With Mews',
        unit: '%',
        min: 0,
        max: 2,
        step: 0.05,
        displayMode: 'target',
      },
    },
    {
      key: 'payment.reconciliationTimeDaily',
      slice: 'payment',
      field: 'reconciliationTimeDaily',
      label: 'Daily Reconciliation Time',
      question: 'How many hours does your team spend on payment reconciliation each day?',
      benchmarkLabel: 'Hotels typically spend 2-4 hours daily',
      unit: 'hrs',
      min: 0,
      max: 8,
      step: 0.25,
      group: 'payments',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: 'Daily reconciliation time based on HFTP surveys and Mews research across hotel finance teams measuring manual payment reconciliation processes.',
      mewsMapping: {
        slice: 'payment',
        field: 'mewsReconciliationTimeDaily',
        label: 'With Mews',
        unit: 'hrs',
        min: 0,
        max: 4,
        step: 0.25,
        displayMode: 'target',
      },
    },
    {
      key: 'payment.noShowRate',
      slice: 'payment',
      field: 'noShowRate',
      label: 'No-Show Rate',
      question: 'What percentage of reservations are no-shows?',
      benchmarkLabel: `${hotelType}s average 2-3%`,
      unit: '%',
      min: 0,
      max: 15,
      step: 0.5,
      group: 'payments',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `No-show rates for ${hotelType}s based on STR/CoStar data and hospitality industry research reports.`,
      mewsMapping: {
        slice: 'payment',
        field: 'noShowWithoutFee',
        label: 'Fee Recovery Rate',
        unit: '%',
        min: 0,
        max: 100,
        step: 5,
        displayMode: 'additive',
      },
    },

    // ── Group 3: Revenue (finance team often knows) ──────────────────
    {
      key: 'guestExperience.currentDirectBookingPercent',
      slice: 'guestExperience',
      field: 'currentDirectBookingPercent',
      label: 'Current Direct Booking %',
      question: 'What percentage of your bookings are currently direct (not via OTAs)?',
      benchmarkLabel: `${hotelType === 'Boutique Hotel' ? '30' : '25'}% typical for ${hotelType}s`,
      unit: '%',
      min: 0,
      max: 100,
      step: 5,
      group: 'revenue',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Direct booking percentage for ${hotelType}s based on Phocuswright and CBRE Hotels research on distribution mix.`,
      mewsMapping: {
        slice: 'guestExperience',
        field: 'directBookingIncrease',
        label: 'Direct Booking Uplift',
        unit: '%',
        min: 0,
        max: 100,
        step: 5,
        displayMode: 'uplift',
      },
    },
    {
      key: 'guestExperience.averageCommission',
      slice: 'guestExperience',
      field: 'averageCommission',
      label: 'OTA Commission Rate',
      question: 'What commission rate do you pay on OTA bookings?',
      benchmarkLabel: 'OTAs typically charge 15-20%',
      unit: '%',
      min: 0,
      max: 30,
      step: 1,
      group: 'revenue',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: 'OTA commission rates based on publicly available rate cards from major OTAs (Booking.com, Expedia) and CBRE Hotels research on distribution costs.',
    },
    {
      key: 'guestExperience.currentCheckInPercentage',
      slice: 'guestExperience',
      field: 'currentCheckInPercentage',
      label: 'Online Check-In Adoption',
      question: '',
      benchmarkLabel: '~8% industry avg without active promotion',
      unit: '%',
      min: 0,
      max: 100,
      step: 1,
      group: 'revenue',
      importance: 'medium',
      validationOnly: true,
      benchmarkSourceInfo: 'Baseline online check-in adoption without Mews based on Mews June 2025 survey data (8.6% global portal avg). Mews target varies by region (15–35%) and hotel type.',
      mewsMapping: {
        slice: 'guestExperience',
        field: 'onlineCheckInPercentage',
        label: 'With Mews',
        unit: '%',
        min: 0,
        max: 100,
        step: 5,
        displayMode: 'growth',
      },
    },
  ];

  // ── Group 4: RMS (always shown — hasExistingRMS question gates the module) ──
  inputs.push(
      {
        key: 'rms.hotelRevPAR',
        slice: 'rms',
        field: 'hotelRevPAR',
        label: 'Current RevPAR',
        question: '',
        benchmarkLabel: 'ADR x Occupancy % (auto-calculated)',
        unit: currencySymbol,
        min: 1,
        max: 500,
        step: 5,
        group: 'rms',
        importance: 'high',
        validationOnly: true,
        readOnly: true,
        benchmarkSourceInfo: `Revenue per available room derived from ADR and occupancy rate for ${hotelType} properties.`,
        mewsMapping: {
          slice: 'rms',
          field: 'estimatedRevenueUplift',
          label: 'Revenue Uplift',
          unit: '%',
          min: 0,
          max: 25,
          step: 0.5,
          displayMode: 'uplift',
        },
      },
      {
        key: 'rms.numberOfRatePlans',
        slice: 'rms',
        field: 'numberOfRatePlans',
        label: 'Number of Rate Plans',
        question: 'How many rate plans does your property manage (BAR, corporate, group, packages, etc.)?',
        benchmarkLabel: `Typical for ${hotelType}s`,
        unit: 'plans',
        min: 1,
        max: 20,
        step: 1,
        group: 'rms',
        importance: 'high',
        skipLabel: 'Use industry average',
        benchmarkSourceInfo: `Typical number of rate plans for ${hotelType} properties based on HFTP research and Mews operator interviews.`,
      },
      {
        key: 'rms.numberOfChannels',
        slice: 'rms',
        field: 'numberOfChannels',
        label: 'Number of Channels',
        question: 'How many distribution channels do you update rates on (OTAs, GDS, direct, tour operators)?',
        benchmarkLabel: `Typical for ${hotelType}s`,
        unit: 'channels',
        min: 1,
        max: 15,
        step: 1,
        group: 'rms',
        importance: 'high',
        skipLabel: 'Use industry average',
        benchmarkSourceInfo: `Typical number of distribution channels for ${hotelType} properties based on HFTP and Phocuswright research.`,
      },
      {
        key: 'rms.rateChangesPerWeek',
        slice: 'rms',
        field: 'rateChangesPerWeek',
        label: 'Rate Changes per Week',
        question: 'How many times per week do you typically update your rates?',
        benchmarkLabel: `Industry average: ${
          hotelType === 'Serviced Apartment' ? '2'
          : hotelType === 'Boutique Hotel' ? '3'
          : hotelType === 'Conference Hotel' ? '5'
          : '7'
        }/week`,
        unit: '/week',
        min: 0.25,
        max: 14,
        step: 0.25,
        group: 'rms',
        importance: 'high',
        skipLabel: 'Use industry average',
        benchmarkSourceInfo: `Rate update frequency based on HFTP surveys and Mews research across revenue management teams.`,
        mewsLabel: 'Auto Pilot',
      },
      {
        key: 'rms.avgTimeToUpdateRate',
        slice: 'rms',
        field: 'avgTimeToUpdateRate',
        label: 'Time per Rate Update',
        question: 'How many minutes does it take to update a single rate across your channels?',
        benchmarkLabel: 'Industry average 3-8 min per update',
        unit: 'min',
        min: 1,
        max: 15,
        step: 0.5,
        group: 'rms',
        importance: 'high',
        skipLabel: 'Use industry average',
        benchmarkSourceInfo: `Average time per manual rate update based on HFTP research and Mews operator interviews across revenue management teams.`,
        mewsLabel: 'Instant',
      },
  );

  // ── Group 5: Housekeeping ────────────────────────────────────────
  inputs.push(
    {
      key: 'housekeeping.departureCleanTime',
      slice: 'housekeeping',
      field: 'departureCleanTime',
      label: 'Departure Room Clean Time',
      question: 'How many minutes does it take to clean a room after a guest departs?',
      benchmarkLabel: `${hotelType === 'Short-Term Rental' ? '60' : hotelType === 'Serviced Apartment' ? '50' : hotelType === 'Boutique Hotel' ? '35' : '30'} min typical · sets HK staff count`,
      unit: 'min',
      min: 15,
      max: 120,
      step: 5,
      group: 'housekeeping',
      importance: 'high',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Used with stayover clean time and occupancy to calculate how many housekeeping staff are needed per day. More staff = more time saved from Mews room assignment automation.`,
    },
    {
      key: 'housekeeping.stayoverCleanTime',
      slice: 'housekeeping',
      field: 'stayoverCleanTime',
      label: 'Stayover Room Clean Time',
      question: 'How many minutes does a stayover service take per room?',
      benchmarkLabel: hotelType === 'Short-Term Rental' ? 'N/A — set to 0 for short-term rentals' : '20 min typical · enables cleaning status savings',
      unit: 'min',
      min: 0,
      max: 60,
      step: 5,
      group: 'housekeeping',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Also contributes to the HK staff calculation. When greater than 0, it unlocks the Cleaning Status Updates savings lever (time saved from real-time room status vs manual checks).`,
    },
    {
      key: 'housekeeping.hkStaffOnDuty',
      slice: 'housekeeping',
      field: 'hkStaffOnDuty',
      label: 'HK Staff on Duty',
      question: '',
      benchmarkLabel: 'Auto-calculated from rooms, occupancy and clean times above',
      unit: 'staff',
      min: 1,
      max: 200,
      step: 1,
      group: 'housekeeping',
      importance: 'high',
      readOnly: false,
      validationOnly: true,
      benchmarkSourceInfo: 'Number of housekeeping staff needed per day, derived from daily room volume and clean times. Drives the Room Assignment Automation and Cleaning Status savings levers. You can override this manually if you know your actual staffing.',
    },
    {
      key: 'housekeeping.amenityCostPerRoomNight',
      slice: 'housekeeping',
      field: 'amenityCostPerRoomNight',
      label: 'Amenity Cost per Room Night',
      question: 'How much do you spend on amenities (toiletries, minibar restocking, etc.) per occupied room night?',
      benchmarkLabel: `${hotelType === 'Boutique Hotel' ? '€3.00' : hotelType === 'Serviced Apartment' ? '€0.50' : '€1.00'} typical for ${hotelType}s`,
      unit: currencySymbol,
      min: 0.10,
      max: 25,
      step: 0.10,
      group: 'housekeeping',
      importance: 'medium',
      skipLabel: 'Use industry average',
      benchmarkSourceInfo: `Amenity cost per room night for ${hotelType} properties based on AHLA operational cost benchmarks and Mews research.`,
      mewsMapping: {
        slice: 'housekeeping',
        field: 'amenityReductionPct',
        label: 'Reduction with Mews',
        unit: '%',
        min: 0,
        max: 20,
        step: 1,
        displayMode: 'additive',
      },
    },
  );

  // Filter by enabled modules if provided
  if (enabledModules) {
    return inputs.filter((input) => {
      // Always include property group
      if (input.group === 'property') {
        return true;
      }
      // Include operations and revenue only if guestExperience is enabled
      if ((input.group === 'operations' || input.group === 'revenue') && !enabledModules.guestExperience) {
        return false;
      }
      // Include payments only if payment is enabled
      if (input.group === 'payments' && !enabledModules.payment) {
        return false;
      }
      // Include rms only if rms is enabled
      if (input.group === 'rms' && !enabledModules.rms) {
        return false;
      }
      // Include housekeeping only if housekeeping is enabled
      if (input.group === 'housekeeping' && !enabledModules.housekeeping) {
        return false;
      }
      return true;
    });
  }

  return inputs;
}

// Group definitions for display
export const INPUT_GROUPS = {
  property: {
    label: 'Your Property',
    description: 'The basics about your hotel',
    icon: 'Building2',
  },
  operations: {
    label: 'Operations',
    description: 'How your property runs day-to-day',
    icon: 'Clock',
  },
  payments: {
    label: 'Payments',
    description: 'Payment processing and reconciliation',
    icon: 'CreditCard',
  },
  revenue: {
    label: 'Revenue',
    description: 'Revenue streams and distribution',
    icon: 'TrendingUp',
  },
  rms: {
    label: 'Revenue Management',
    description: 'Rate plans, channels, and pricing frequency',
    icon: 'BarChart3',
  },
  housekeeping: {
    label: 'Housekeeping',
    description: 'Room cleaning times and amenity costs',
    icon: 'BedDouble',
  },
} as const;
